name: "Make Release Action"
description: "Run Make Release"
author: "Nexient DevSecOps"

inputs:
  mode:
    description: "Sets the versioning type to use. For options see https://github.com/restechnica/semverbot#modes"
    default: "auto"
runs:
  using: "composite"
  steps:
    - name: make release
      run: |
        mode=${{ inputs.mode }} \
        make release
      shell: bash
