name: "Run Pre-merge"
description: "Run Pre-merge"
author: "Nexient DevSecOps"

inputs:
  branch:
    description: "target branch to conduct pre-merge check with"
    default: "origin/main"
runs:
  using: "composite"
  steps:
    - name: fetch main
      run: |
        git fetch --all
      shell: bash
    - name: "pre-merge"
      run: |
        git merge --no-commit --no-ff "${{ inputs.branch }}" && echo -e "Merge simulation successful" || exit 1
      shell: bash
