name: pipeline-release
on:
  pull_request:
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.repository.name, 'tf-')
    container:
      image: nexientdevops/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/configure
        with:
          JOB_NAME: "job"
          JOB_EMAIL: "job@job.job"
      - uses: ./.github/actions/check
      - uses: ./.github/actions/pre-merge
      - uses: ./.github/actions/release
