on:
  push:
    branches:
      - main

jobs:
  make_release_job:
    runs-on: ubuntu-latest
    name: Make Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Docker Action
        uses: actions/make-docker-action@v1
        with:
          target: release
