on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  make_check_job:
    runs-on: ubuntu-latest
    name: Make Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Make Docker Action
        uses: actions/make-docker-action@v1
        with:
          target: check
