name: "Make Configure Action"
description: "Run Make Configure"
author: "Nexient DevSecOps"

inputs:
  IS_AUTHENTICATED:
    description: "Denotes if git-auth target should run"
    default: false
  IS_PIPELINE:
    description: "Denote if running in a pipeline context"
    default: true
  JOB_NAME:
    description: "Sets the git user's name for the job"
    default: "nexient-github-sa"
    required: true
  JOB_EMAIL:
    description: "Sets the git user's email for the job"
    default: "service-account@nexient.com"
    required: true
  REPO_MANIFESTS_URL:
    description: "The repository containing the repo manifest"
    default: "https://github.com/nexient-llc/module-manifests.git"
  REPO_BRANCH:
    description: "The branch to point to for the repo manifest"
    default: "main"
  REPO_MANIFEST:
    description: "The file in the repo manifest repository that contains the manifest's index"
    default: "tf_modules.xml"
  COMPONENTS_DIR:
    description: "Directory for components to be installed to"
    default: "components"
runs:
  using: "composite"
  steps:
    - name: fix github known_hosts issues
      shell: bash
      run: mkdir -m 0700 -p ~/.ssh && ssh-keyscan github.com | tee -a ~/.ssh/known_hosts
    - name: git safe directory
      shell: bash
      run: |
        git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
    - name: make configure
      shell: bash
      run: |
        REPO_MANIFESTS_URL=${{ inputs.REPO_MANIFESTS_URL }} \
        REPO_BRANCH=${{ inputs.REPO_BRANCH }} \
        REPO_MANIFEST=${{ inputs.REPO_MANIFEST }} \
        COMPONENTS_DIR=${{ inputs.COMPONENTS_DIR }} \
        IS_AUTHENTICATED=${{ inputs.IS_AUTHENTICATED }} \
        JOB_NAME=${{ inputs.JOB_NAME }} \
        JOB_EMAIL=${{ inputs.JOB_EMAIL }} \
        IS_PIPELINE=${{ inputs.IS_PIPELINE }} \
        make configure
