# This file is managed by https://github.com/nexient-llc/.github/

# DO NOT make changes to this file directly from within any other
# repo then mentioned above as they will be overwritten upon the
# next sync.

name: pipeline-check
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: nexientdevops/platform-images
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/configure
        with:
          JOB_NAME: "job"
          JOB_EMAIL: "job@job.job"
      - uses: ./.github/actions/check
      - uses: ./.github/actions/pre-merge
