name: sync-global-workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '!.github/workflows/sync-global-workflows.yaml'
  workflow_dispatch: 
    inputs:
      repo_name:
        description: |
          You can specify name of the repository where workflows should be pushed manually. As long as repository is not ignored by workflow settings.
          If you do not specify exact repository name, the workflow will try to replicate all missing changes to all repositories.
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Replicating files (platform-tf-modules, platform-magicdust)
        uses: derberg/copy-files-to-other-repositories@v1.0.3
        with:
          github_token: ${{ secrets.WORKFLOW_SYNC_TOKEN }}
          patterns_to_include: .github/workflows/platform-check.yaml,.github/workflows/platform-release.yaml
          patterns_to_ignore: .github/workflows/sync-global-workflows.yaml
          topics_to_include: platform-tf-module, platform-magicdust
          exclude_private: true
          exclude_forked: true
          branches: main
          committer_username: nexient-github-sa
          committer_email: service-account@nexient.com
          commit_message: 'ci: update platform terraform module workflows'
      - name: Replicating files (platform-module-manifest)
        uses: derberg/copy-files-to-other-repositories@v1.0.3
        with:
          github_token: ${{ secrets.WORKFLOW_SYNC_TOKEN }}
          patterns_to_include: .github/workflows/basic-check.yaml,.github/workflows/basic-release.yaml
          patterns_to_ignore: .github/workflows/sync-global-workflows.yaml
          topics_to_include: platform-module-manifest, platform-component
          exclude_private: true
          exclude_forked: true
          branches: main
          committer_username: nexient-github-sa
          committer_email: service-account@nexient.com
          commit_message: 'ci: update platform workflows'